name: Injection Test

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue title
        run: echo "New issue title is: ${{ github.event.issue.title }}"
